### PR TITLE
Add support for tables and strike-through text in the XSLT

### PR DESCRIPTION
**Pull request by maelle**
this PR adds support for tables and strike-through text to @nwellnhof's useful XSLT stylesheet.

The tables obtained are not "pretty", i.e. each column header gets three dashes only.

Cc @jeroen

### CODE REVIEW

**Comment by jeroen** [comment]
This is great! @nwellnhof would you have any suggestions for improvements?

**Comment by nwellnhof** [comment]
It looks like this won't work with table cells containing multiple lines. Supporting multiple lines probably requires a two-pass approach and the [EXSLT `node-set`](http://exslt.org/exsl/functions/node-set/index.html) extension.

**Comment by nwellnhof** [comment]
I'd also suggest to put the templates handling GHF extensions in a separate stylesheet and import the core stylesheet with `xsl:import`. This way, you can simply overwrite the core `xml2md.xsl` file whenever it is changed upstream.

**Comment by maelle** [comment]
:wave: @nwellnhof ! Thanks for your review!
* Good point about the separate stylesheets, will do!
* I'm afraid I do not understand what you mean by "a two-pass approach and the EXSLT node-set extension." Could you please provide pointers or an example? Thank you in advance!

**Comment by kivikakk** [comment]
We don't support table cells with multiple lines as it stands, so I think it's a non-issue.

@maelle Let me know when this is ready for merge (if you plan on separating out the extensions).

**Comment by maelle** [comment]
I've now made it a separate stylesheet. 😸 

I didn't know multilines tables weren't supported, one problem less then.

I added a small comment inside the stylesheet to explain what it is.

Btw I was wondering whether/where the two stylesheets should be documented, i.e. how would someone know they even exist.

**Comment by kivikakk** [comment]
> I've now made it a separate stylesheet. 😸

Awesome, thank you!

> Btw I was wondering whether/where the two stylesheets should be documented, i.e. how would someone know they even exist.

This is a good point — @jgm, do you have any thoughts/opinions here? Right now `xml2md.xsl` is buried in the `tools` directory and no reference to it is made. I'm not a consumer of this, so I wouldn't know where I _would_ go looking for documentation/pointers to such a thing if I was one.

**Comment by jgm** [comment]
Ashe Connor <notifications@github.com> writes:

> This is a good point — @jgm, do you have any
> thoughts/opinions here? Right now `xml2md.xsl` is
> buried in the `tools` directory and no reference to
> it is made. I'm not a consumer of this, so I
> wouldn't know where I _would_ go looking for
> documentation/pointers to such a thing if I was one.

I'm not really sure.  It could be put in the README,
I suppose, along with a pointer to the dtd documenting
the XML format.

**Comment by maelle** [comment]
@jgm I'd be happy to open a PR to the commonmark/cmark repo. Maybe a subsection of "Usage" in the README could be "Misc" and mention the stuff in https://github.com/commonmark/cmark/tree/master/tools including the stylesheet. 
* If I do that could I add a sentence about the complementary XSLT stylesheet living in the github fork? 
* What are the other files in tools/, are they worth mentioning in the README?
* I'd also add a pointer to the docs of the XML format in another subsection at the same time if that's useful. :-)

**Pull request merged**
