### PR TITLE
> 32 nested balanced parens in a link is bananas

### PR DESCRIPTION
**Pull request by kivikakk**
Fixes https://github.com/jgm/cmark/issues/214.

/cc @mity @vmg

### CODE REVIEW

**Comment by vmg** [comment]
:seemsgood: :seemsgood:

What does the output look like when you hit the threshold? That's a good thing to know and document. Does it just show the plain Markdown syntax?

**Comment by kivikakk** [comment]
Yep — it's just treated as broken syntax, same as if the parens weren't nested correctly at all. Any idea where this is best documented?

**Comment by vmg** [comment]
I was leaning towards "in the spec", but again I believe this should be a corner case that should never be hit during normal Markdown usage, so I'm not sure there's value on documenting it explicitly.

Let's wait and see who complains. :)

**Comment by Alhadis** [comment]
MY LISP CODE.

WHAT HAVE YOU DONE?!

(I kid, I kid))))))))))))))))))))))))))))))))))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))))]]]]]]]]]]]]]]]]]]]]]]]]
((((((((((((((((((((((((((O)))))))))))))))))))))))))))))))))))))

**Pull request merged**
